mongo_connection: "mongodb://$MONGO_USER:$MONGO_PASSWORD@$MONGO_HOST"
mongo_db: "$MONGO_DB"
mongo_options:
  uuidRepresentation: "standard"

loki:
  url: ${APP_HOST}/loki/api/v1/push

# TODO: multiple stores support?
minio:
  endpoint: "http://carrier-minio:9000"
  region: "us-east-1"
  access_key: "$MINIO_ACCESS_KEY"
  secret_key: "$MINIO_SECRET_KEY"
  secure: false
  verify: false

rabbitmq:
  host: "$RABBIT_HOST"
  port: 5672
  user: "$RABBIT_USER"
  password: "$RABBIT_PASSWORD"
  timeout: 15
  vhost: "carrier"
  all_queue: "tasklets-arbiter-all"

runner:
  pylon:
    loki:
      buffering: false
      buffer_capacity: 70
      include_node_name: true
      include_level_name: true
      include_logger_name: true
      verify: true
      url: ${LOKI_HOST_INTERNAL}
    #
    # "vault": {}
    #
    # TODO: multiple stores support?
    #
    storage:
      endpoint: "http://carrier-minio:9000"
      region: "us-east-1"
      access_key: "$MINIO_ACCESS_KEY"
      secret_key: "$MINIO_SECRET_KEY"
      secure: false
      verify: false
    #
    rpc:
      rabbitmq:
        host: "rabbitmq"
        port: 5672
        user: "user"
        password: "password"
        vhost: "carrier"
        queue: "rpc"
        hmac_key: "key"
        hmac_digest: "sha512"
        callback_workers: 16
      id_prefix: "worker_"
      # TODO: check prefix and make it uniq
    #
    events:
      rabbitmq:
        host: "rabbitmq"
        port: 5672
        user: "user"
        password: "password"
        vhost: "carrier"
        queue: "tasklets-events"
        hmac_key: "key"
        hmac_digest: "sha512"
        callback_workers: 16
  #
  provider:
    name: "pylon.core.providers.source.git"
    args:
      delete_git_dir: false
      depth: null
